const translateButton = document.getElementById('translate-button');
const paragraphs = document.querySelectorAll('p');
const headers = document.querySelectorAll('h2');

let isRussian = true;

translateButton.addEventListener('click', () => {
    if (isRussian) {
        headers.forEach((h2) => {
            h2.textContent = h2.textContent.replace(/Introduction/g, 'Введение');
            h2.textContent = h2.textContent.replace(/History/g, 'История');
            h2.textContent = h2.textContent.replace(/Steam/g, 'Стим');
            h2.textContent = h2.textContent.replace(/VR Technologies/g, 'Технологии ВР');
            h2.textContent = h2.textContent.replace(/Self-Organization/g, 'Само-организация');
            h2.textContent = h2.textContent.replace(/Steam-Machines/g, 'Стим-машина');
            h2.textContent = h2.textContent.replace(/Conclusion/g, 'Заключение');
        });
        paragraphs.forEach((p) => {
            p.textContent = p.textContent.replace(/Valve Corporation is one of the most prominent game developers in the world. Over its more than twenty-year history, the company has created numerous popular games, such as Half-Life, Counter-Strike, Dota 2, Portal, and Team Fortress 2. However, Valve not only creates games but also pays great attention to technology development and innovation in the gaming industry./g, 'Компания Valve является одним из наиболее заметных игровых разработчиков в мире. За свою более чем двадцатилетнюю историю компания создала множество популярных игр, таких как Half-Life, Counter-Strike, Dota 2, Portal и Team Fortress 2. Однако, Valve не только создает игры, но и уделяет большое внимание развитию технологий и инновациям в игровой индустрии.');
            p.textContent = p.textContent.replace(/Valve Corporation was founded in 1996 by Gabe Newell and Mike Harrington, who had previously worked at Microsoft. The name "Valve" was chosen to emphasize the importance of the technologies that control the flow of information in the game. The first game released by the company was the first-person shooter Half-Life, which came out in 1998 and immediately became iconic and successful. After that, Valve released many other games that became legendary in the gaming industry./g, 'Компания Valve была основана в 1996 году Гейбом Ньюэллом и Майком Херстом, которые ранее работали на Microsoft. Название "Valve" было выбрано для того, чтобы подчеркнуть значимость технологий, которые контролируют поток информации в игре. Первой игрой, которую выпустила компания, был шутер от первого лица Half-Life, который вышел в 1998 году и стал сразу же культовым и успешным. После этого Valve выпустила еще множество игр, которые стали легендарными в игровой индустрии.');
            p.textContent = p.textContent.replace(/However, Valve is famous not just for its games but for its platform for digital game distribution called Steam. In 2002, the company introduced this platform, which was the first of its kind on the market. Today, Steam is the largest platform for buying and downloading games in the world. Steam offers a wide selection of games for PC, Mac, and Linux, as well as social network features such as voice chats, messaging, user profiles, and more. On Steam, you can buy or download many games, including games from other developers./g, 'Однако, Valve славится не только своими играми, но и платформой для цифровой дистрибуции игр, называемой Steam. В 2002 году компания представила эту платформу, которая стала первой в своем роде на рынке. Сегодня Steam является крупнейшей платформой для покупки и скачивания игр в мире. Steam предлагает широкий выбор игр для PC, Mac и Linux, а также функции социальной сети, такие как голосовые чаты, обмен сообщениями, профиль пользователя и другие. На Steam можно купить или скачать бесплатно множество игр, в том числе и игры других разработчиков.');
            p.textContent = p.textContent.replace(/In addition, Valve pays great attention to the development of VR technologies. In 2016, the company released its first VR headset, the HTC Vive, which received many positive reviews. Developers also created the SteamVR toolset, which is used to create virtual reality./g, 'Кроме того, Valve уделяет большое внимание развитию VR-технологий. В 2016 году компания выпустила свой первый VR-шлем HTC Vive, который получил множество положительных отзывов. Разработчики также создали набор инструментов SteamVR, который используется для создания виртуальной реальности.');
            p.textContent = p.textContent.replace(/Another interesting feature of Valve is its non-traditional organizational structure. The company is built on principles of self-organization and equality among employees. Instead of having a rigid hierarchical structure, Valve attracts talented and creative developers from all over the world, who work on projects in a free-form manner. This working model allows the company to attract the best specialists in the industry, as well as create unique and interesting games and technologies. It has become one of the main reasons for Valve's success and attracted the attention of other companies in the gaming industry./g, 'Еще одна интересная особенность Valve - это ее нетрадиционная организационная структура. Компания построена на принципах самоорганизации и равенства сотрудников. Вместо того, чтобы иметь жесткую иерархическую структуру, Valve привлекает талантливых и креативных разработчиков со всего мира, которые работают над проектами в свободной форме. Эта модель работы позволяет компании привлекать лучших специалистов в индустрии, а также создавать уникальные и интересные игры и технологии. Она стала одной из основных причин успеха Valve и привлекла внимание других компаний в игровой индустрии.');
            p.textContent = p.textContent.replace(/Another interesting project from Valve was Steam Machines - gaming PCs that run on the SteamOS operating system and are designed for use in the living room. This project was launched in 2013 as an attempt by Valve to expand its presence in the gaming device market but did not gain widespread popularity. The concept behind Steam Machines was to create devices that would be available at a price comparable to Sony and Microsoft consoles but with PC capabilities. However, the project faced problems such as a limited selection of games and the need to use the specialized SteamOS operating system. Moreover, there were already devices based on Windows on the market, which made competition for Steam Machines even more challenging. Ultimately, Valve discontinued the sale of Steam Machines in 2018./g, 'Еще одним интересным проектом Valve была Steam Machines - игровые ПК, которые работают на операционной системе SteamOS и предназначены для использования в гостиной. Этот проект был запущен в 2013 году, как попытка Valve расширить свое присутствие на рынке игровых устройств, но не получил широкого распространения. Концепция Steam Machines заключалась в том, чтобы создать устройства, которые будут доступны по цене, сравнимой с консолями от Sony и Microsoft, но с возможностями PC. Однако, проект столкнулся с проблемами, такими как ограниченный выбор игр и необходимость использования специальной операционной системы SteamOS. Кроме того, на рынке уже были устройства, основанные на Windows, что сделало конкуренцию Steam Machines еще более сложной. В итоге, Valve прекратила продажу Steam Machines в 2018 году.');
            p.textContent = p.textContent.replace(/Valve Corporation is one of the most successful game developers and innovators in the gaming industry. Its Steam platform has become the largest in the world, and VR technologies and non-traditional organizational structure help the company continue to develop and remain competitive. Valve continues to work on new technologies and games, so its contribution to the industry will continue to grow in the future./g, 'Компания Valve является одной из наиболее успешных игровых разработчиков и инноваторов в игровой индустрии. Ее платформа Steam стала крупнейшей в мире, а VR-технологии и нетрадиционная организационная структура помогают компании продолжать развиваться и оставаться конкурентоспособной. Valve продолжает работать над новыми технологиями и играми, поэтому ее вклад в индустрию будет продолжать расти в будущем.');
        });
        translateButton.textContent = 'РУС';
    } else {
        headers.forEach((h2) => {
            h2.textContent = h2.textContent.replace(/Введение/g, 'Introduction');
            h2.textContent = h2.textContent.replace(/История/g, 'History');
            h2.textContent = h2.textContent.replace(/Стим/g, 'Steam');
            h2.textContent = h2.textContent.replace(/Технологии ВР/g, 'VR Technologies');
            h2.textContent = h2.textContent.replace(/Само-организация/g, 'Self-Organization');
            h2.textContent = h2.textContent.replace(/Стим-машина/g, 'Steam-Machines');
            h2.textContent = h2.textContent.replace(/Заключение/g, 'Conclusion');
        });
        paragraphs.forEach((p) => {
            p.textContent = p.textContent.replace(/Компания Valve является одним из наиболее заметных игровых разработчиков в мире. За свою более чем двадцатилетнюю историю компания создала множество популярных игр, таких как Half-Life, Counter-Strike, Dota 2, Portal и Team Fortress 2. Однако, Valve не только создает игры, но и уделяет большое внимание развитию технологий и инновациям в игровой индустрии./g, 'Valve Corporation is one of the most prominent game developers in the world. Over its more than twenty-year history, the company has created numerous popular games, such as Half-Life, Counter-Strike, Dota 2, Portal, and Team Fortress 2. However, Valve not only creates games but also pays great attention to technology development and innovation in the gaming industry.');
            p.textContent = p.textContent.replace(/Компания Valve была основана в 1996 году Гейбом Ньюэллом и Майком Херстом, которые ранее работали на Microsoft. Название "Valve" было выбрано для того, чтобы подчеркнуть значимость технологий, которые контролируют поток информации в игре. Первой игрой, которую выпустила компания, был шутер от первого лица Half-Life, который вышел в 1998 году и стал сразу же культовым и успешным. После этого Valve выпустила еще множество игр, которые стали легендарными в игровой индустрии./g, 'Valve Corporation was founded in 1996 by Gabe Newell and Mike Harrington, who had previously worked at Microsoft. The name "Valve" was chosen to emphasize the importance of the technologies that control the flow of information in the game. The first game released by the company was the first-person shooter Half-Life, which came out in 1998 and immediately became iconic and successful. After that, Valve released many other games that became legendary in the gaming industry.');
            p.textContent = p.textContent.replace(/Однако, Valve славится не только своими играми, но и платформой для цифровой дистрибуции игр, называемой Steam. В 2002 году компания представила эту платформу, которая стала первой в своем роде на рынке. Сегодня Steam является крупнейшей платформой для покупки и скачивания игр в мире. Steam предлагает широкий выбор игр для PC, Mac и Linux, а также функции социальной сети, такие как голосовые чаты, обмен сообщениями, профиль пользователя и другие. На Steam можно купить или скачать бесплатно множество игр, в том числе и игры других разработчиков./g, 'However, Valve is famous not just for its games but for its platform for digital game distribution called Steam. In 2002, the company introduced this platform, which was the first of its kind on the market. Today, Steam is the largest platform for buying and downloading games in the world. Steam offers a wide selection of games for PC, Mac, and Linux, as well as social network features such as voice chats, messaging, user profiles, and more. On Steam, you can buy or download many games, including games from other developers.');
            p.textContent = p.textContent.replace(/Кроме того, Valve уделяет большое внимание развитию VR-технологий. В 2016 году компания выпустила свой первый VR-шлем HTC Vive, который получил множество положительных отзывов. Разработчики также создали набор инструментов SteamVR, который используется для создания виртуальной реальности./g, 'In addition, Valve pays great attention to the development of VR technologies. In 2016, the company released its first VR headset, the HTC Vive, which received many positive reviews. Developers also created the SteamVR toolset, which is used to create virtual reality.');
            p.textContent = p.textContent.replace(/Еще одна интересная особенность Valve - это ее нетрадиционная организационная структура. Компания построена на принципах самоорганизации и равенства сотрудников. Вместо того, чтобы иметь жесткую иерархическую структуру, Valve привлекает талантливых и креативных разработчиков со всего мира, которые работают над проектами в свободной форме. Эта модель работы позволяет компании привлекать лучших специалистов в индустрии, а также создавать уникальные и интересные игры и технологии. Она стала одной из основных причин успеха Valve и привлекла внимание других компаний в игровой индустрии./g, 'Another interesting feature of Valve is its non-traditional organizational structure. The company is built on principles of self-organization and equality among employees. Instead of having a rigid hierarchical structure, Valve attracts talented and creative developers from all over the world, who work on projects in a free-form manner. This working model allows the company to attract the best specialists in the industry, as well as create unique and interesting games and technologies. It has become one of the main reasons for Valves success and attracted the attention of other companies in the gaming industry.');
            p.textContent = p.textContent.replace(/Еще одним интересным проектом Valve была Steam Machines - игровые ПК, которые работают на операционной системе SteamOS и предназначены для использования в гостиной. Этот проект был запущен в 2013 году, как попытка Valve расширить свое присутствие на рынке игровых устройств, но не получил широкого распространения. Концепция Steam Machines заключалась в том, чтобы создать устройства, которые будут доступны по цене, сравнимой с консолями от Sony и Microsoft, но с возможностями PC. Однако, проект столкнулся с проблемами, такими как ограниченный выбор игр и необходимость использования специальной операционной системы SteamOS. Кроме того, на рынке уже были устройства, основанные на Windows, что сделало конкуренцию Steam Machines еще более сложной. В итоге, Valve прекратила продажу Steam Machines в 2018 году./g, 'Another interesting project from Valve was Steam Machines - gaming PCs that run on the SteamOS operating system and are designed for use in the living room. This project was launched in 2013 as an attempt by Valve to expand its presence in the gaming device market but did not gain widespread popularity. The concept behind Steam Machines was to create devices that would be available at a price comparable to Sony and Microsoft consoles but with PC capabilities. However, the project faced problems such as a limited selection of games and the need to use the specialized SteamOS operating system. Moreover, there were already devices based on Windows on the market, which made competition for Steam Machines even more challenging. Ultimately, Valve discontinued the sale of Steam Machines in 2018.');
            p.textContent = p.textContent.replace(/Компания Valve является одной из наиболее успешных игровых разработчиков и инноваторов в игровой индустрии. Ее платформа Steam стала крупнейшей в мире, а VR-технологии и нетрадиционная организационная структура помогают компании продолжать развиваться и оставаться конкурентоспособной. Valve продолжает работать над новыми технологиями и играми, поэтому ее вклад в индустрию будет продолжать расти в будущем./g, 'Valve Corporation is one of the most successful game developers and innovators in the gaming industry. Its Steam platform has become the largest in the world, and VR technologies and non-traditional organizational structure help the company continue to develop and remain competitive. Valve continues to work on new technologies and games, so its contribution to the industry will continue to grow in the future.');
        });
        translateButton.textContent = 'ENG';
    }
    isRussian = !isRussian;
});